# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dswidgets',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/dswidgets',
                'lib_path': 'dswidgets'},
  'syms': { 'dswidgets.Buttons': { 'dswidgets.Buttons.Toggle': ('buttons.html#toggle', 'dswidgets/Buttons.py'),
                                   'dswidgets.Buttons.Toggle.__init__': ('buttons.html#toggle.__init__', 'dswidgets/Buttons.py'),
                                   'dswidgets.Buttons.Toggle.toggle_cb': ('buttons.html#toggle.toggle_cb', 'dswidgets/Buttons.py')},
            'dswidgets.FileSystem': {'dswidgets.FileSystem.FolderSelector': ('filesystem.html#folderselector', 'dswidgets/FileSystem.py')}}}
