# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Buttons.ipynb.

# %% auto 0
__all__ = ['Toggle']

# %% ../nbs/00_Buttons.ipynb 4
import panel as pn
import sys

# %% ../nbs/00_Buttons.ipynb 13
class Toggle:
  """
  A `panel` toggle button with customizable properties.  The button's name and
  color is set according to the state of the button. If a user call back `change_cb`
  is given, it will be called each time the button is toggled.  A list will be 
  passed containing the `id` and the `state` of the button.
  """
  def __init__(self, 
               initial_state = 0,              # The initial button state upon creation.
                          id = '',             # An identifier string.
                     on_name = 'Data is On',   # Message displayed on the button when in ON state
                    off_name = 'Data is Off',  # Message displayed on button when in Off state
                    on_color = 'primary',      # Color when ON
                   off_color = 'danger',       # Color when Off
                   change_cb = None,           # An optional user call back function called when toggled.
              ):
    self.initial_state  = initial_state
    self.id             = id
    self.state          = state  = initial_state
    self.value          = state
    self.change_cb      = change_cb
    self.name           = [1,2]
    self.color          = [1,2]
    self.cb             = [1,2]
    self.button_type    = [1,2]
    self.name[0]        = off_name
    self.color[0]       = off_color
    self.button_type[0] = 'danger'
    self.name[1]        = on_name
    self.color[1]       = on_color
    self.button_type[1] = 'primary'
    self.button = pn.widgets.Button(name = self.name[ state ] , button_type = self.button_type[state] )
    rv = self.button.on_click( self.toggle_cb )

  def toggle_cb(self, event):   # Execute this every time the button is pressed.
    if self.state == 0:
      self.state   = int(1)
    else:
      self.state   = int(0)
         
    state      = self.state
    self.value = state
    self.button.name    = self.name[state] 
    self.button.button_type = self.button_type[ state ]
    if self.change_cb:
      self.change_cb( [self.id, self.state] )
      
